version: '1'

services:
  dating-app-v1:
    container_name: dating-app
    image: ghcr.io/sphexi/dating_app:main
    restart: unless-stopped
    environment:
      - DB_USER=
      - DB_PASSWORD=
      - DB_NAME=
      - DB_HOST=
      - DB_PORT=
    ports:
      - 8555:8080